// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof require !== "undefined" && require !== null) {
    document.lastChild.className += ' ' + 'gui blur';
  }

}).call(this);

/*
//@ sourceMappingURL=gui.map
*/
