// Generated by CoffeeScript 1.6.3
(function() {
  var mycard_client_connect, mycard_client_start, mycard_version, set_status, ygopro_version;

  $('#login_form').submit(function() {
    bootbox.dialog({
      message: '正在登录...'
    });
    $('#login_form button[type=submit]').attr('disabled', 'disabled');
    return false;
  });

  $.getJSON('http://my-card.in/announcements.json', function(data) {
    var announcement, _i, _len, _ref, _results;
    $('#announcements').empty();
    _ref = data.slice(0, 9);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      announcement = _ref[_i];
      _results.push($('<li/>').append($('<a/>', {
        href: announcement.url,
        text: announcement.title,
        "class": 'select'
      })).appendTo('#announcements'));
    }
    return _results;
  });

  mycard_version = null;

  ygopro_version = null;

  set_status = function(text) {
    if (!text) {
      text = "MyCard 版本: " + mycard_version;
      if (ygopro_version) {
        text += " / YGOPro 版本: " + (/^[a-fA-F0-9]{16}$/.test("ygopro_version") ? '未知' : ygopro_version);
      }
    }
    return $('#mycard_status').text(text);
  };

  mycard_client_connect = function(wait) {
    var connected, mycard_client;
    if (wait == null) {
      wait = 5;
    }
    connected = false;
    mycard_client = new WebSocket('ws://127.0.0.1:9998/');
    mycard_client.onopen = function(evt) {
      connected = true;
      $('.col-md-8').append($('<a/>', {
        id: "test",
        text: "测试"
      }));
      return $('#test').click(function() {
        mycard_client.send("mycard://122.0.65.69:7911/test");
        return false;
      });
    };
    mycard_client.onclose = function(evt) {
      console.log('连接关闭');
      if (!connected) {
        if (wait > 1) {
          return mycard_client_connect(wait - 1);
        } else {
          return bootbox.alert("启动本地客户端失败");
        }
      } else {
        $('#mycard_status').text('本地客户端连接中断, 正在重新连接...');
        return mycard_client_start();
      }
    };
    return mycard_client.onmessage = function(evt) {
      var msg;
      msg = JSON.parse(evt.data);
      console.log(msg);
      if (msg.version != null) {
        mycard_version = msg.version;
        set_status();
      }
      if (msg.ygopro_version != null) {
        ygopro_version = msg.ygopro_version;
        set_status();
      }
      if (msg.images_download_images != null) {
        if (msg.images_download_images === 0 && msg.images_download_thumbnails === 0) {
          return set_status();
        } else {
          return set_status("正在下载卡图 缩略: " + msg.images_download_images + " 完整: " + msg.images_download_thumbnails + " 错误: " + msg.images_download_errors);
        }
      }
    };
  };

  mycard_client_start = function() {
    $('<iframe/>', {
      src: 'mycard:///',
      hidden: true
    }).appendTo('body');
    return mycard_client_connect();
  };

  set_status('Loading...');

  mycard_client_start();

}).call(this);

/*
//@ sourceMappingURL=lobby.map
*/
